### ISSUE TITLE
Update module to support Youtube v11.27.53

### ISSUE THREAD

**Issue by aamir1995** [Ashish-Bansal/OneTapYoutubeModule#2]
Hi! it's been a week since the latest release of youtube is out, Can you please update the module to support Youtube app version 11.27.53.
Thanks :)

**Comment by Ashish-Bansal** [comment]
Hi Aamir,

Actually I didn't have internet connection till today morning. Currently I'm setting up development environment. So, I'll release update after that.

Regards,
Ashish Bansal

**Comment by aamir1995** [comment]
@Ashish Thanks for your support, Can't wait to see new update :)

**Comment by Ashish-Bansal** [comment]
Fixed with @a5c676b96031767f4235556c720cb44fb2a174fa
