### ISSUE TITLE
It suddnly stop working

### ISSUE THREAD

**Issue by RoxasXII** [Ashish-Bansal/OneTapYoutubeModule#4]
It stop working after updating the YouTube and I can't figure out how to solve it plz help !

**Comment by woronka182** [comment]
use an older version of YouTube, https://www.apkmirror.com/apk/google-inc/youtube/

**Comment by Ashish-Bansal** [comment]
Now it should work with latest version of youtube(12.21.57). 
https://github.com/Ashish-Bansal/OneTapVideoDownload/pull/54
